jenkinsci/pipeline-maven-plugin

- src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
@reviewbybees esp @jnord @amuniz
> Improve computer handling

- src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
> JENKINS-38709 - Merge previous console log filter instead of overriding it.

- pom.xml
- src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
- src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
- src/main/resources/index.jelly
- src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
[JENKINS-39134](https://issues.jenkins-ci.org/browse/JENKINS-39134)
Fixes the symptom, pending some understanding of the root problem.
@reviewbybees
> [JENKINS-39134] Work around Guice problem

- src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
https://issues.jenkins-ci.org/browse/JENKINS-40142
@reviewbybees
> [FIX JENKINS-40142]  - Correctly set default values for String params

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
Improve console messages and simplify code execution path.
Sample
```
[Pipeline] withMaven
[withMaven] use JDK installation provided by the build agent
[withMaven] use Maven installation 'maven-3.3.9'
[withMaven] use Maven settings provided by the Jenkins Managed Configuration File 'settings-for-multi-module-maven-project'
[withMaven] use Maven settings.xml 'settings-for-multi-module-maven-project' with Maven servers credentials provided by Jenkins (replaceAll: true): [mavenServerId: 'nexus.beescloud.com', jenkinsCredentials: 'beescloud-nexus-deployment-credentials', username: 'deployment', type: 'UsernamePasswordCredentialsImpl'], [mavenServerId: 'github.com', jenkinsCredentials: 'github-credentials', username: 'cyrille-leclerc', type: 'UsernamePasswordCredentialsImpl']
```
> Improve console messages and simplify code execution path.

- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-mavenLocalRepo.html
Better help message based on the proposal of #13 by @jtnord
> Better help message based on the proposal of #13

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/GeneratedArtifactsReporter.java
[JENKINS-42300](https://issues.jenkins-ci.org/browse/JENKINS-42300) Handle maven artifact file not found and unexpected exceptions.
Sample:
```
[withMaven] FAILURE to archive maven-site-plugin/dependency-reduced-pom.xml under org/apache/maven/plugins/maven-site-plugin/3.7-SNAPSHOT/maven-site-plugin-3.7-SNAPSHOT.pom, file not found
```
> [JENKINS-42300] Handle maven artifact file not found and unexpected exceptions.

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
[JENKINS-43341](https://issues.jenkins-ci.org/browse/JENKINS-43341) Protect code against NullPointerException and throw IllegalStateException in case of uncertain code path
> [JENKINS-43341] Protect code against NullPointerException

- jenkins-plugin/pom.xml
- maven-spy/pom.xml
Add @cyrille-leclerc as developer
> Add cleclerc as developer

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/GeneratedArtifactsReporter.java
[JENKINS-43617](https://issues.jenkins-ci.org/browse/JENKINS-43617) better exception message and better logging to help understand the root cause.
> [JENKINS-43617] better exception message and better logging

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java
[JENKINS-39407](https://issues.jenkins-ci.org/browse/JENKINS-39407) Use Maven Settings and Maven Global Settings defined in the Jenkins Global Configuration
> [JENKINS-39407] Use Maven Settings and Maven Global Settings defined in the Jenkins Global Configuration

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/JunitTestsReporter.java
- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java
- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/FailsafeTestExecutionHandler.java
Added listener for failsafe plugin
Adjusted JUnit reporter for failsafe plugin
> Added support for failsafe plugin

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/reporters/GeneratedArtifactsReporterTest.java
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-windows.xml
[JENKINS-43624](https://issues.jenkins-ci.org/browse/JENKINS-43624) Fix file separator on windows build agents
> [JENKINS-43624] Fix file separator on windows build agents

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher.java
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher/config.jelly
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher/help-asRegexp.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher/help-disabled.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher/help-excludePattern.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher/help-highPriorityTaskIdentifiers.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher/help-ignoreCase.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher/help-lowPriorityTaskIdentifiers.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher/help-normalPriorityTaskIdentifiers.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher/help-pattern.html
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java
[JENKINS-44386](https://issues.jenkins-ci.org/browse/JENKINS-44386) Add configuration options to the OpenTasksPublisher
```groovy
withMaven(options:[openTasksPublisher(
pattern:'src/main/java', excludePattern:'src/main/java/excluded',
ignoreCase:true, asRegexp:false, 
lowPriorityTaskIdentifiers:'minor', normalPriorityTaskIdentifiers:'todo', highPriorityTaskIdentifiers:'fixme')]) {
sh 'mvn package verify'
}
```
> [JENKINS-44386] Add configuration options to the OpenTasksPublisher

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisher/config.jelly
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisher/help-disabled.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisher/help.html
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyFingerprintPublisherTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/MavenPublisherTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessorTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisherTest.java
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy.xml
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/mono_dependency_maven_jar_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/mono_dependency_maven_jar_project/pom.xml
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/mono_dependency_maven_jar_project/src/main/java/com/example/App.java
- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/DependencyResolutionResultHandler.java
[JENKINS-43094](https://issues.jenkins-ci.org/browse/JENKINS-43094) Add fingerprinting of Maven Dependencies
> WIP [JENKINS-43094] Add fingerprinting of Maven Dependencies

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/GeneratedArtifactsPublisher.java
[JENKINS-44807](https://issues.jenkins-ci.org/browse/JENKINS-44807) Don't forget to track the usage of the fingerprinted generated artifacts.
> [JENKINS-44807] Don't forget to track the usage of the fingerprinted generated artifacts

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessorTest.java
- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/DependencyResolutionResultHandler.java
isSnapshot didn't behave as expected. I shouldn't have included it in the original pull request.
> Pass snapshot status explicitly

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
[JENKINS-40484](https://issues.jenkins-ci.org/browse/JENKINS-40484) Better troubleshooting messages
> [JENKINS-40484] Better troubleshooting messages

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
[JENKINS-46159](https://issues.jenkins-ci.org/browse/JENKINS-46159) track credentials usage
> [JENKINS-46159] track credentials usage

- Jenkinsfile
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/console/MaskPasswordsConsoleLogFilter.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/console/MaskSecretsOutputStream.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/console/MavenColorizerConsoleLogFilter.java
[JENKINS-46342](https://issues.jenkins-ci.org/browse/JENKINS-46342) mask passwords injected in settings.xml via the config file provider plugin
> [JENKINS-46342] mask passwords injected in settings.xml via the config file provider plugin

- jenkins-plugin/pom.xml
Workaround until https://github.com/jenkinsci/junit-attachments-plugin/pull/18 is released.
@reviewbybees
> [INFRA-1310] Avoid bogus Stapler transitive dep

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
[JENKINS-46517] better logging level
> [JENKINS-46517] better logging level

- README.md
- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/reporter/FileMavenEventReporter.java
- maven-spy/src/test/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpyMTTest.java
- pom.xml
Add some tests to check concurrency issues and a fix to make sure file is unique.
cc - @cyrille-leclerc
> JENKINS-46579 -  Concurrency problems with spy log

- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java
- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/DeployDeployExecutionHandler.java
Track "mvn deploy" details: add the pom.distributionManagementArtifactoryRepository
> Track "mvn deploy" details

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesLister.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JGivenTestsPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/PipelineGraphPublisher.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/MavenPublisherTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesListerTest.java
> JENKINS-45887 : Fix TU and avoid workspace scan if not necessary

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginDao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2Dao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginNullDao.java
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig/config.jelly
[JENKINS-47589](https://issues.jenkins-ci.org/browse/JENKINS-47589) Better details of the database status for better troubleshooting
> [JENKINS-47589] Better details of the database status for better troubleshooting

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java
[JENKINS-47823](https://issues.jenkins-ci.org/browse/JENKINS-47823) Make `withMaven` compatible with docker-pipeline:1.14
> [JENKINS-47823] Make withMaven compatible with docker-pipeline:1.14

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java
[JENKINS-48264] Support whitespace in pipeline name
> [JENKINS-48264] Support whitespace in pipeline name

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2Dao.java
[JENKINS-46577] Better detection of plugin loading issues. Detect when the ".sql" files bundled in the plugin are not found by the Thread Context Class Loader
> [JENKINS-46577] Better detection of plugin loading issues

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2Dao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/ClassUtils.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/ClassUtilsTest.java
[JENKINS-46577] Better resource loading: use the pipeline plugin classloader in addition to the thread context class loader.
> [JENKINS-46577] Better resource loading 

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher.java
[JENKINS-44359](https://issues.jenkins-ci.org/browse/JENKINS-44359) tasksScanner - handle Maven builds with NO source code processed by Maven.
> [JENKINS-44359] tasksScanner - handle Maven builds with NO source code processed by Maven.

- jenkins-plugin/README.md
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java
[JENKINS-48678] Cleanup log messages
> [JENKINS-48678] Cleanup log messages

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenPublisherStrategy.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/config.jelly
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-publisherStrategy.html
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/MavenPublisherStrategyTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
Replaces https://github.com/jenkinsci/pipeline-maven-plugin/pull/116
> [JENKINS-46785] Strategy to enable / disable publishers in pipelines

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
```
[withMaven] Maven installation not specified in the 'withMaven()' step 
and not found on the build agent but 'mvnw' script found in the workspace.
```
> JENKINS-49721 support `mvnw` maven installation

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2Dao.java
[JENKINS-50852] Deduplicate pipeline build dependencies list
> [JENKINS-50852] Deduplicate pipeline build dependencies list

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher.java
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher/config.jelly
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher/help-healthScaleFactor.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher/help-keepLongStdio.html
[JENKINS-50916](https://issues.jenkins-ci.org/browse/JENKINS-50916) Add support for JUnit health factor attribute
> [JENKINS-50916] Add support for JUnit health factor attribute

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginMonitoringDao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncItemListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncRunListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/MavenReport.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
[JENKINS-51086] Replace static lookups of dependencies by @Inject
[JENKINS-51087] Add monitoring of the SQL calls
> Jenkins 51086 & JENKINS-51087

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/MavenLinkerPublisher2.java
[JENKINS-51922](https://issues.jenkins-ci.org/browse/JENKINS-51922) prevent thread safety issues on the MavenReport Action
> [JENKINS-51922] prevent thread safety issues on the MavenReport Action

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
[JENKINS-53378] Better message in build logs when the trigger of downstream pipeline is skipped
```
[withMaven] Not triggering my-war » master because it has a dependency on a pipeline that will be triggered by this build: my-jar-2 » master
[withMaven] Scheduling downstream pipeline my-war#68..
```
```
[withMaven] Not triggering my-webapp because it has a dependency already building or in queue: my-other-pipeline
```
```
[withMaven] Infinite loop detected: not triggering my-artifact-end-to-end-tests (dependency: com.example:my-artifact:jar:1.0-SNAPSHOT) because it is itself triggering this pipeline my-artifact (dependency: com.example:my-artifact:jar:1.0-SNAPSHOT)
```
> [JENKINS-53378] Better message in build logs when the trigger of downstream pipeline is skipped

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
[JENKINS-53380](https://issues.jenkins-ci.org/browse/JENKINS-53380) Trigger downstream pipelines only once when multiple generated artifacts of upstream are dependencies
```
[withMaven] Scheduling downstream pipeline my-downstream-pipeline#62 due to dependency on com.example:my-jar:jar:0.7-SNAPSHOT(0.7-20180902.093122-80),  com.example:my-other-jar:jar:0.7-SNAPSHOT(0.7-20180902.093137-80)...
```
> [JENKINS-53380] Trigger downstream pipelines only once when multiple generated artifacts of upstream are dependencies

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/cause/MavenDependencyCause.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/cause/MavenDependencyUpstreamCause.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/cause/MavenDependencyUpstreamCause/description.jelly
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/cause/MavenDependencyUpstreamCause/description.properties
[JENKINS-53392](https://issues.jenkins-ci.org/browse/JENKINS-53392) Support multiple maven artifacts as the cause of a MavenDependencyUpstreamCause
> [JENKINS-53392] Support multiple maven artifacts as the cause of a MavenDependencyUpstreamCause

- jenkins-plugin/pom.xml
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisher.java
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisher/config.jelly
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisher/help-disabled.html
- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisher/help.html
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/AbstractIntegrationTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/MavenPublisherStrategyTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_jacoco_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_jacoco_project/pom.xml
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_jacoco_project/src/main/java/com/example/MonoModuleMavenApp.java
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_jacoco_project/src/test/java/com/example/MonoModuleMavenAppIT.java
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_jacoco_project/src/test/java/com/example/MonoModuleMavenAppTest.java
JENKINS-53755 detect and publish JaCoCo Code Coverage Reports
> JENKINS-53755 detect and publish JaCoCo Code Coverage Reports

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenArtifact.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/cause/MavenDependencyCauseHelper.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginDao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2Dao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginMonitoringDao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginNullDao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/service/PipelineTriggerService.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/cause/MavenDependencyCauseHelperTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2DaoTest.java
JENKINS-54011 prevent duplicate triggers for the same upstream artifact
> JENKINS-54011 prevent duplicate triggers for the same upstream artifact

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/ConcordionTestsPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/FindbugsAnalysisPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/InvokerRunsPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/SpotBugsAnalysisPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtilsTest.java
JENKINS-54139 Jacoco: don't automatically publish report if more than 1 Maven module has generated a jacoco report
> JENKINS-54139 Jacoco: don't automatically publish report if more than 1 Maven module has generated a jacoco report

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/AbstractPipelineMavenPluginDao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginMonitoringDao.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/AbstractIntegrationTest.java
JENKINS-54669 JENKINS-54661 fix datasource properties loading + use sensible default settings for the datasource
> JENKINS-54669 JENKINS-54661 fix datasource properties loading + use sensible default settings for the datasource

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/AbstractPipelineMavenPluginDao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2Dao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginMySqlDao.java
JENKINS-54784 Verify the database version in the validation of the jdbc connection
> JENKINS-54784 Verify the database version in the validation of the jdbc connection

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/cause/MavenDependencyCliCause.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/cli/TriggerDownstreamPipelinesCommand.java
```
jenkins-cli trigger-downstream-pipelines --groupId com.example --artifactId my-jar --type=jar --version 0.7-SNAPSHOT
```
> JENKINS-54845 Add CLI command trigger-downstream-pipelines

- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java
- maven-spy/src/test/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandlerTest.java
- maven-spy/src/test/resources/org/jenkinsci/plugins/pipeline/maven/eventspy/pom-flatten-plugin-flattenedPomFilename.xml
- maven-spy/src/test/resources/org/jenkinsci/plugins/pipeline/maven/eventspy/pom-flatten-plugin-flattenedPomFilename2.xml
JENKINS-55010 better detection of temporary file name of  pom.xml when using "flatten-maven-plugin" and overwriting the default "flattenedPomFilename" setting
> JENKINS-55010 better detection of temporary file name of  pom.xml when using "flatten-maven-plugin"

- .mvn/extensions.xml
- .mvn/maven.config
- jenkins-plugin/pom.xml
- maven-spy/pom.xml
- pom.xml
Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/38 though no actual code changes yet; see [other work](https://github.com/jenkinsci/pipeline-maven-plugin/compare/JENKINS-49337).
> [JENKINS-49337] Incrementalified and prepped for consuming GeneralNonBlockingStepExecution

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
JENKINS-55325 Display warning message if a Maven settings '<server>' definition is skipped because the Jenkins credentials are NOT found
> JENKINS-55325 Warning message when '<server>' def is skipped due to missing credentials

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/AbstractPipelineMavenPluginDao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2v1Dao.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginDaoAbstractTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2v1DaoTest.java
JENKINS-55566 only one downstream pipeline per parent pom dependency is triggered even if there are multiple downstream pipelines
> JENKINS-55566 only one downstream pipeline per parent pom dependency is triggered

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
JENKINS-57145 Reduce message length when withMaven(){} is running in docker.image("").inside{}
> JENKINS-57145 Reduce message length when withMaven(){} is running in docker.image("").inside{}

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenArtifact.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/AbstractPipelineMavenPluginDao.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2v1Dao.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginDaoAbstractTest.java
JENKINS-57332 fix mix of artifact.version and artifact.baseVersion in PipelineMavenPluginDao#getGeneratedArtifacts()
> JENKINS-57332 fix mix of artifact.version and artifact.baseVersion in PipelineMavenPluginDao#getGeneratedArtifacts()

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2Test.java
I have changed the fix to only affect pathnames.  This would allow in future to make use of the positional arguments in the wrapper script if so required.  I am testing this on windows.
> Jenkins 57324

- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java
JENKINS-56666 file name is ".git-versioned-pom.xml", not ".git-versioned.pom.xml"
> JENKINS-56666 file name is ".git-versioned-pom.xml", not ".git-versioned.pom.xml"

- jenkins-plugin/pom.xml
JENKINS-57794 use the mysql-api-plugin to load the mysql-java-connector jar
> JENKINS-57794 use the mysql-api-plugin to load the mysql-java-connector jar

- jenkins-plugin/pom.xml
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/AbstractIntegrationTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/cause/MavenDependencyCauseHelperTest.java
- jenkins-plugin/src/test/java/org/jvnet/hudson/test/ExtendedToolInstallations.java
- pom.xml
JENKINS-57813 Bump jenkins-core dependency to 2.138 and bump the maven engine used in unit tests to 3.6.1
> JENKINS-57813 Bump jenkins-core dependency to 2.138

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/service/PipelineTriggerService.java
JENKINS-58784 adapt withMaven downstream pipeline trigger to be compatible with JENKINS-22949 (Authorize Project Plugin...)
Change: logging improvement + real change copied below 
```java
// BEFORE
Authentication auth = Tasks.getAuthenticationOf(downstreamPipeline);
// jenkins.triggers.ReverseBuildTrigger#shouldTrigger
Authentication downstreamPipelineAuth;	
if (auth.equals(ACL.SYSTEM) && !QueueItemAuthenticatorConfiguration.get().getAuthenticators().isEmpty()) {	
downstreamPipelineAuth = Jenkins.ANONYMOUS; // cf. BuildTrigger	
} else {	
downstreamPipelineAuth = auth;	
}
// AFTER
Authentication downstreamPipelineAuth = Tasks.getAuthenticationOf(downstreamPipeline);
```
> JENKINS-58784 adapt withMaven downstream pipeline trigger to be compatible with JENKINS-22949

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
JENKINS-57794 recommend to install the "MySQL API Plugin" / "PostgreSQL API Plugin" when the JDBC driver class is not found
> JENKINS-57794 recommend to install the "MySQL API Plugin" / "PostgreSQL API Plugin" when the JDBC driver class is not found

- jenkins-plugin/pom.xml
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher.java
https://issues.jenkins-ci.org/browse/JENKINS-59583
Not sure about test coverage. On my windows box with git bash, I tried running tests _before_ this change and saw many failures, so I didn't bother...
> JENKINS-59583 set stage result/warning

- maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java
- pom.xml
Cleaned up the empty elses in AbstractMavenEventHandler.
> Maint cleanup elses

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/MavenReport.java
For full compatibility with https://github.com/jenkinsci/jenkins/pull/4848.
> Check either Acegi or Spring Security version of AccessDeniedException, or AccessDeniedException2 or AccessDeniedException3

- .mvn/extensions.xml
https://github.com/jenkinsci/incrementals-tools
> Upgrade Jenkins incremental to latest (1.1)

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisher.java
> fix typos in JacocoReportPublisher

- .github/release-drafter.yml
This plugin uses semver and the release name = tag
> Update Release Drafter config

- jenkins-plugin/pom.xml
- maven-spy/pom.xml
- pom.xml
+ add the check in the build to keep them formatted
> [chore] Use the tidy:pom maven plugin to unify the project POMs

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
Just a hotfix, I will append integration tests later
- [N/A] Link to relevant pull requests, esp. upstream and downstream changes
> hotfix: [JENKINS-63670] add versions up to 13 as supported PostgreSQL versions

- .github/CODEOWNERS
- ~[ ] Link to relevant issues in GitHub or Jira~
- ~[ ] Link to relevant pull requests, esp. upstream and downstream changes~
- ~[ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~
> chore: Use the dev team as CODEOWNER

- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/AbstractIntegrationTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_docker_base_project/pom.xml
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_docker_dependency_project/pom.xml
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_docker_dependency_project/src/main/docker/Dockerfile
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_hpi_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_flatten_pom_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_jacoco_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_parent_pom_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_nbm_base_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_nbm_dependency_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_plugin_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_war_project/.gitignore
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/mono_dependency_maven_jar_project/.gitignore
> chore: add integration test for JENKINS-59500

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JGivenTestsPublisher.java
First check presence of companion plugin before anything else
> [JENKINS-48935] Clearer jgiven publisher console output when jgiven plugin is not installed

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/FindbugsAnalysisPublisher.java
First check presence of companion plugin before anything else
> [JENKINS-48937] Clearer findbugs publisher console output when findbugs plugin is not installed

- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-maven.html
> Fix typo in the documentation of the withMaven step

- jenkins-plugin/pom.xml
- maven-spy/pom.xml
Remove default values, sort dependencies by scope
> cleanup POMs

- README.adoc
link ConfigurationAsCode examples to help configuring
See https://issues.jenkins.io/browse/JENKINS-65001
> JENKINS-65001: link ConfigurationAsCode examples to help configuring

- jenkins-plugin/pom.xml
- pom.xml
Jenkins LTS switched from 2.303.x to 2.319.x, so upgrade our baseline too.
> update Jenkins baseline to 2.303.x

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesLister.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JGivenTestsPublisher.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/PipelineGraphPublisher.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesListerTest.java
Fix https://issues.jenkins.io/browse/JENKINS-68741 by using a Set instead of a List
> fix JENKINS-68741 : Build dependencies are recorded several times in database

- pom.xml
> Adding myself as a developper

- jenkins-plugin/pom.xml
- maven-spy/pom.xml
- pom.xml
> chore(pom): cleanup and regroup versions in parent

- jenkins-plugin/pom.xml
- maven-spy/pom.xml
- pom.xml
> chore(pom): replace tidy with sortpom plugin to allow auto format AND auto sort of POMs

- jenkins-plugin/pom.xml
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyFingerprintPublisherTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepGlobalConfigurationTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListenerIntegrationTest.java
- pom.xml
> chore: update to 2.319.x LTS baseline

- pom.xml
Reverts jenkinsci/pipeline-maven-plugin#498
> Revert "build(deps): bump plugin from 4.45 to 4.46"

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
> Fix FAQ URL which is displayed during the build step

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitor.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitorIntegrationTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitorTest.java
fix https://issues.jenkins.io/browse/JENKINS-62358
> fix JENKINS-62358: NonProductionGradeDatabaseWarningAdministrativeMonitor slowing down startup

- jenkins-plugin/pom.xml
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/db/migration/h2/MigrationStep11.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncItemListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncRunListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/service/PipelineTriggerService.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/trigger/WorkflowJobDependencyTrigger.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListenerTest.java
> chore: do not depend on workflow-job for production code

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/AbstractWorkflowRunListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncRunListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncRunListenerTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListenerIntegrationTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListenerTest.java
Fix https://issues.jenkins.io/browse/JENKINS-62407
> fix JENKINS-62407: Builds displaying "downstreamPipelineTriggerRunListener" when not configured to do so

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtilsTest.java
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-deploy-2.8.xml
- jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-deploy-3.0.xml
https://issues.jenkins.io/browse/JENKINS-69410
> fix JENKINS-69410: Links to Deployed Artifacts broken with maven-deploy-plugin 3.0.0

- jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitor/message.jelly
Adopts https://github.com/jenkinsci/jenkins/pull/7364
cc @jenkinsci/pipeline-maven-plugin-developers I'd appreciate it, if you could cut a release afterwards :)
> Forward compatibility with jenkins-buttons

- jenkins-plugin/pom.xml
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/SqlTestsUtils.java
- pom.xml
> chore: update baseline to 2.346

- FAQ.adoc
Provided an example with docker for declarative pipelines
---
- [na] Link to relevant issues in GitHub or Jira
- [na] Link to relevant pull requests, esp. upstream and downstream changes
- [na] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> [doc] provide declarative pipeline example 

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncItemListener.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/trigger/WorkflowJobDependencyTrigger.java
> bugfix: dependency trigger is not visible anymore in configuration page

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
https://issues.jenkins.io/browse/JENKINS-71073
> bugfix: Snippet generator fails: No enum constant org.jenkinsci.plugins.pipeline.maven.MavenPublisherStrategy (JENKINS-71073)

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitor.java
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/CustomTypePipelineMavenPluginDaoDecorator.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepNoOptionalsTest.java
See https://issues.jenkins.io/browse/JENKINS-71123
> bugfix: NoClassDefFoundError: org/apache/commons/lang3/StringUtils (JENKINS-71123)

- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
Amendment to #670 to correct a confusing (but harmless) NPE shown in the build log when the agent did not get reattached after a controller restart:
```
…
[Pipeline] // withMaven
[Pipeline] }
[Pipeline] }
[Pipeline] // node
[Pipeline] // container
[Pipeline] }
Agent was removed
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: …
java.lang.NullPointerException
at org.jenkinsci.plugins.pipeline.maven.WithMavenStepExecution2$WithMavenStepExecutionCallBack.finished(WithMavenStepExecution2.java:1111)
at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$TailCall.lambda$onSuccess$0(GeneralNonBlockingStepExecution.java:140)
at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
at …
```
> NPE in `WithMavenStepExecutionCallBack.finished`

- Jenkinsfile
- jenkins-plugin/pom.xml
- jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/AbstractIntegrationTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfigTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitorIntegrationTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepNoOptionalsTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginMySqlDaoIT.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginPostgreSqlDaoIT.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/publishers/InvokerRunsPublisherInternalTest.java
- jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtilsTest.java
> enable windows builds

- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeNeedDockerTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfigTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/console/MaskPasswordsConsoleLogFilterTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/FakeCredentialsProvider.java
> chore: reuse same class for faking credentials

- README.adoc
- pipeline-maven-database/src/main/java/org/jenkinsci/plugins/pipeline/maven/db/AbstractPipelineMavenPluginDao.java
- pipeline-maven/src/main/resources/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig/help-jdbcUrl.html
I'm not sure if we have some automated tests, but I can only confirm it works
See
```[tasklist]
```
> Add support for PostgreSQL 15 and 16

- README.adoc
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
See https://issues.jenkins.io/browse/JENKINS-51182
```[tasklist]
```
> feature: Conceal console lines from Maven downloads [JENKINS-51182]

- pom.xml
> chore: switch to 2.387 baseline

- Jenkinsfile
- pipeline-maven-database/src/main/java/org/jenkinsci/plugins/pipeline/maven/db/PipelineMavenPluginH2Dao.java
- pipeline-maven/pom.xml
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
- pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/JavasContainer/Dockerfile
- pom.xml
> chore: enable Java21 build

- FAQ.adoc
See also: https://github.com/takari/maven-wrapper
> Replace deprecated Takari wrapper with official one in README

- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
https://issues.jenkins.io/browse/JENKINS-72516
```[tasklist]
```
> fix JENKINS-72516: warning of unknown Maven version

- pipeline-maven-api/pom.xml
- pipeline-maven-api/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenArtifact.java
- pipeline-maven-api/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginDao.java
- pipeline-maven-database/pom.xml
- pipeline-maven/pom.xml
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/NeededPipelineMavenDatabasePluginAdminMonitor.java
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisher.java
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesLister.java
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/GeneratedArtifactsPublisher.java
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher.java
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeNeedDockerTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepNoOptionalsTest.java
- pom.xml
Signed-off-by: Olivier Lamy <olamy@apache.org>
```[tasklist]
```
> cleanup some dependencies not needed to be included in hpi

- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
This PR reverts changes made in #766
> Drop detecting of execution inside container()

- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeNeedDockerTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfigTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepMavenExecResolutionTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/docker/JavaGitContainerTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListenerIntegrationTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/Conditions.java
- pom.xml
> chore: switch to 2.414 baseline

- pipeline-maven/pom.xml
Signed-off-by: Olivier Lamy <olamy@apache.org>
> do not run docker build when tests are skipped

- pom.xml
> chore: deploy all artifacts at the end of a release

- pipeline-maven/pom.xml
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfigTest.java
- pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
- pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_publishers.yml
- pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_publishers.yml
> chore: improve configuration coverage

- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
When executing in a docker agent, the call to MasterToSlaveFileCallable will not execute on the docker agent, but on the launcher agent.
Changes the code to use launcher.launch() like in the readFromProcess() method which is aware of the launcher decorator.
[JENKINS-72516 pipeline-maven: warning of unknown Maven version in plugin version 1368.vfb_8509d7b_869](https://issues.jenkins.io/browse/JENKINS-72516) 
Tested with and without docker. Tested on Windows also. 
Before:
```
[withMaven] Options: []
[withMaven] Available options: 
[withMaven] IMPORTANT "withMaven(){...}" step running within a Docker container. See 
[Pipeline Maven Plugin FAQ](https://github.com/jenkinsci/pipeline-maven-plugin/blob/master/FAQ.adoc#how-to-use-the-pipeline-maven-plugin-with-docker) in case of problem. …
```
> JENKINS-72516 fix WARNING: You are running an old version of Maven

- pipeline-maven/pom.xml
- pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/CoveragePublisher.java
See [JENKINS-75966](https://issues.jenkins.io/browse/JENKINS-75966)
1. Build the PR changes locally and generate the 999999-SNAPSHOT.hpi file.
2. Launch jenkins.war locally and navigate to Manage Jenkins → Plugin Manager → Installed Plugins.
3. Ensure that the pipeline-maven-api, pipeline-maven, and coverage plugins are not installed.
4. Using the Jenkins UI, install the SNAPSHOT version of the pipeline-maven-api plugin, followed by the pipeline-maven 5. plugin.
5. Return to the Installed Plugins tab and check whether the coverage plugin has been installed.
6. Confirm that the coverage plugin was not installed as a dependency of the pipeline-maven plugin. :tada:
> Mark coverage plugin as optional
