jenkinsci/pipeline-maven-plugin

src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java

Hi Alavaro,
we recently moved to Jenkins 2 and we like the pipeline-maven-plugin very much. However we noticed that a certain build showed an odd behavior. We narrowed it down to a batch file, that behaved differently when executed "withMaven". The batch file basically looked like
mvn.bat some:goal && some-other-cmd
Outside of withMaven both commands got executed as expected. Inside we noticed that some-other-cmd (and everything else following this line) was omitted. The problem here is that the pipeline-maven-plugin forcibly sets the MAVEN_TERMINATE_CMD variable to "on". This causes the mvn.bat script (the original apache-maven version) to call exit %errorcode% instead of exit /b %errorcode%. The trouble is, the former exit command causes the batch execution to stop completely so that …

MAVEN_TERMINATE_CMD is no longer overriden

---

src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/config.groovy
src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-globalMavenSettingsConfig.html
src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-globalMavenSettingsFilePath.html

Hi,
We use a lot global settings in your Jenkins to store platform wide settings such as http proxy. Users use maven setting to store project specific settings.
So we need to be able to configure both.
Best wishes,
Julien

Add global maven settings handling

---

pom.xml
src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java

https://issues.jenkins-ci.org/browse/JENKINS-39916
The new version of the config-file-provider supports configfiles on folder levels (also nested folders). This PR adds support for the newest version of the config-file-provider.
It updates dependency to the latest (still beta) version of the config-file-provider plugin. The beta version of the config-file-provider plugin is available in the experimental update center.
Please have a look at this PR and let me know it is OK - I will prepare the release of the config-file-provider plugin soon. (...there are multiple plugins I have to update)

JENKINS-39916 update config-file-provider plugin

---

jenkins-plugin/pom.xml
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java

[JENKINS-42179](https://issues.jenkins-ci.org/browse/JENKINS-42179) use the JAVA_TOOL_OPTIONS environment variable to pass `-Dmaven.ext.class.path` and `-Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder`

[JENKINS-42179] use the JAVA_TOOL_OPTIONS environment variable to pass `-Dmaven.ext.class.path`

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/FindbugsAnalysisReporter.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/GeneratedArtifactsReporter.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/JunitTestsReporter.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/reporters/GeneratedArtifactsReporterTest.java

[JENKINS-42175](https://issues.jenkins-ci.org/browse/JENKINS-42175) Support marker files to disable reporters (archive-artifacts, junit, findbugs…).
It's a kind of temporary / experimental feature to stabilize the plugin. Later, we may introduce a clean API, probably parameters of the "`withMaven(){...}`" step.
Marker file (located in the home directory of the build):
* `.skip-archive-generated-artifacts`: skip the archiving and the fingerprinting of the artifacts and attached artifacts generated by the Maven build (jar, sources jar, javadocs jar...)
* `.skip-publish-junit-results`: skip the publishing of the JUnit / Surefire reports generated by the Maven build
* `.skip-publish-findbugs-results`: skip the publishing of the Findbugs reports generated by the Maven build
Messages displayed …

[JENKINS-42175] Support temporary/experimental marker files to disable reporters (archive-artifacts, junit, findbugs…).

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java

[JENKINS-42302](https://issues.jenkins-ci.org/browse/JENKINS-42302) Tweak Maven project file handling in case of maven-shade-plugin usage.
Ignore temporary project file "dependency-reduced-pom.xml" and use "pom.xml”.

[JENKINS-42302] Tweak Maven project file handling in case of maven-shade-plugin usage.

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/GeneratedArtifactsReporter.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/reporters/GeneratedArtifactsReporterTest.java
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy.xml
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java

[JENKINS-42347](https://issues.jenkins-ci.org/browse/JENKINS-42347) capture generated artifact file extension using the artifact.getArtifactHandler().getExtension() in the Maven Event Spy

[JENKINS-42347] capture generated artifact file extension using the artifact.getArtifactHandler().getExtension() in the Maven Event Spy

---

jenkins-plugin/pom.xml
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java

f563095590299bf94fdf3faf34e26df2b38b4531 removed a faulty test; showing how it should be done. Fails in the expected way if you
git checkout pipeline-maven-parent-2.0-beta-5 -- jenkins-plugin/src/main
(`docker-fixtures` is pretty new so there are not many good examples out there.)
@reviewbybees

Demonstrate SECURITY-441 in a test

---

jenkins-plugin/LICENSE
jenkins-plugin/pom.xml
maven-spy/LICENSE
maven-spy/pom.xml
maven-spy/src/test/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpyDisablementTest.java
pom.xml

Only `org.jenkins-ci.plugins:pipeline-maven` should have `org.jenkins-ci.plugin:plugin` as parent pom. 
`org.jenkins-ci.plugins:pipeline-maven-parent` should not have `org.jenkins-ci.plugin:plugin` as parent pom.

Cleanup pom.xml

---

jenkins-plugin/pom.xml
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/TasksScannerReporter.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtilsTest.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/ProjectFailedExecutionHandler.java

[JENKINS-42606](https://issues.jenkins-ci.org/browse/JENKINS-42606) Integrate with the [Jenkins Task Scanner Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Task+Scanner+Plugin).
* Default configuration
* pattern: `path/to/source/directory/**/*`
* high: `FIXME`
* normal: `TODO`
* Marker file: `.skip-task-scanner`

[JENKINS-42606] Integrate with the Jenkins Tasks Scanner Plugin

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java

When using the plugin on Windows Jenkins Nodes it generates warnings where it shoud not because it uses platform dependent file separators in a string based path comparision.

Use platform independent file separators

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/GeneratedArtifactsReporter.java

[JENKINS-43101](https://issues.jenkins-ci.org/browse/JENKINS-JENKINS-43101) Fix “The fingerprint xyz did not match any of the recorded data.", add the artifacts produced by the maven build to jenkins.fingerprintMap.
ℹ️ I'll add integration tests when merging https://github.com/jenkinsci/pipeline-maven-plugin/tree/add-tests

[JENKINS-43101] Fix “The fingerprint xyz did not match any of the recorded data."

---

maven-spy/pom.xml
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/reporter/FileMavenEventReporter.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/reporter/MavenEventReporter.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/reporter/OutputStreamEventReporter.java

Ensure that the maven-event-spy is thread safe. Ensure that all the implementations of [MavenEventReporter](https://github.com/jenkinsci/pipeline-maven-plugin/blob/pipeline-maven-parent-2.0/maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/reporter/MavenEventReporter.java) are thread safe.
Should fix thread safety issues. See [JENKINS-43159
maven-spy log contains invalid XML](https://issues.jenkins-ci.org/browse/JENKINS-43159)

[JENKINS-43449] Ensure that the maven-event-spy is thread safe

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/reporters/JenkinsMavenEventSpyLogsReporter.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/reporter/FileMavenEventReporter.java

[Jenkins 43491](https://issues.jenkins-ci.org/browse/JENKINS-43491) Feature flag `.archive-jenkins-maven-event-spy-logs` to archive the logs file generated by the Jenkins Maven Event Spy. Primarily intended for troubleshooting purpose.
The `.archive-jenkins-maven-event-spy-logs` has to be created in the Jenkins build workspace.

[Jenkins 43491] Feature flag ".archive-jenkins-maven-event-spy-logs" to archive the logs file generated by the Jenkins Maven Event Spy

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/reporter/FileMavenEventReporter.java
maven-spy/src/test/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpyDisablementTest.java

[JENKINS-43529](https://issues.jenkins-ci.org/browse/JENKINS-43529) Don’t create an invalid build xml logs file when the Maven Event Spy is disabled

[JENKINS-43529] Don’t create an invalid build xml logs file when the Maven Event Spy is disabled

---

jenkins-plugin/pom.xml

[JENKINS-43650](https://issues.jenkins-ci.org/browse/JENKINS-43650) Add dependency to org.jenkins-ci.main:maven-plugin.
Will also be needed to manage global-level and folder-level settings.

[JENKINS-43650] Add dependency to org.jenkins-ci.main:maven-plugin.

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/RuntimeIOException.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/ProjectSucceededExecutionHandler.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/reporter/FileMavenEventReporter.java

[JENKINS-44250](https://issues.jenkins-ci.org/browse/JENKINS-44250) use `File.getCanonicalPath()` instead of `File.getAbsolutePath()` to prevent mismatches between folder paths in the maven-event-spy and the jerkins-plugin

[JENKINS-44250] use File.getCanonicalPath() instead of File.getAbsolutePath()

---

jenkins-plugin/pom.xml
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher.java
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher/config.jelly
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher/help-ignoreAttachments.html

[JENKINS-44226](https://issues.jenkins-ci.org/browse/JENKINS-44226) add support for the jenkins junit-attachments plugin.
Publishing of junit test attachments are enabled by default if the junit-attachments-plugin is installed.
Junit test attachments can be disabled using `options: [junitPublisher(ignoreAttachments: true)]`. Sample:
```groovy
withMaven(
maven:"maven-3.3.9", 
globalMavenSettingsConfig: 'my-global-maven-settings', 
mavenSettingsConfig: 'my-maven-settings',
options: [junitPublisher(ignoreAttachments: true)]) {
sh "mvn clean install"
}
```

[JENKINS-44226] add support for the jenkins junit-attachments plugin

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/InvokerStartExecutionHandler.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/reporter/FileMavenEventReporter.java

By default, IT tests ran by the _maven-invoker-plugin_ will see the `JAVA_TOOL_OPTIONS` environment variable and thus enable the event-spy.
All IT tests runs will be recorded and their artefacts will be archived and fingerprinted as they were from the main project.
But one do not care about that artefacts, they came from test projets.
To avoid this, if we detect the launch of the _maven-invoker-plugin:run_ goal, we append to its configuration the environment variable that will disable the event-spy during IT tests.

JENKINS-45555 : Disable spy through environment when running maven-invoker IT tests

---

jenkins-plugin/pom.xml
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java

As per [JENKINS-19508](https://issues.jenkins-ci.org/browse/JENKINS-19508), you should avoid `optional` dependencies unless you really know what you are doing, and even then you should avoid them, and if you really need to use them you must take care to test the plugin with the dependencies missing.
In this case if `branch-api` is not present but `pipeline-maven-plugin` is, Jenkins explodes when trying to create a new project (not even Pipeline!):
```
java.lang.NoClassDefFoundError: jenkins/branch/MultiBranchProject
at org.jenkinsci.plugins.pipeline.maven.trigger.WorkflowJobDependencyTrigger$DescriptorImpl.isApplicable(WorkflowJobDependencyTrigger.java:30)
```
crashes the job configuration screen.
@reviewbybees

[JENKINS-19508] Eliminate some optional deps

---

jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/trigger/WorkflowJobDependencyTrigger/help.html

there is no point in building something if its dependency is being built (you would have to wait until the thing has been built to be able to use it)
So assuming that the plugin does the right thing and triggers after a dependency has been built and updating the text accordingly.
@cyrille-leclerc I assume you know the behaviour and can say if this is correct text or not.

past tense

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/PipelineGraphPublisher.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-deploy-jar.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-deploy-multi-module.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-nexus-deploy-release.xml

[JENKINS-46511](https://issues.jenkins-ci.org/browse/JENKINS-46511) Option to only trigger downstream pipelines when the generated artifact has been "mvn deploy", not "mvn package" or "mvn install"

[JENKINS-46511] Option to only trigger downstream pipelines when the generated artifact has been "mvn deploy", not "mvn package" or "mvn install"

---

jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/multi_module_bundle_project/pom.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/multi_module_bundle_project/print-api/pom.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/multi_module_bundle_project/print-api/src/main/java/jenkins/mvn/test/bundle/print/PrintService.java
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/multi_module_bundle_project/print-impl/pom.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/multi_module_bundle_project/print-impl/src/main/java/jenkins/mvn/test/bundle/print/impl/PrintServiceImpl.java

A sample project that uses the maven-bundle-plugin to produce
an OSGi bundle.
Modules:
* print-api - OSGi bundle that exports a package containing an API.
* print-impl - Non-OSGi project that consumes the OSGi bundle as a
plain jar dependency.

[JENKINS-47069] Add sample maven-bundle-plugin project

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java

[JENKINS-47013](https://issues.jenkins-ci.org/browse/JENKINS-47013) Fix XML file format when the file path of the working directory contains "--"
Workaround the fact that `org.codehaus.plexus.util.xml.XmlWriterUtil#writeComment(org.codehaus.plexus.util.xml.XMLWriter, java.lang.String)` doesn't escape the reserved char sequence '`--`'

[JENKINS-47013] Fix XML file format when the file path of the working directory contains "--"

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/PipelineGraphPublisher.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/PipelineGraphPublisher/config.jelly
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/PipelineGraphPublisher/help-lifecycleThreshold.html
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtilsTest.java
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-nexus-deploy-release.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-package-jar.xml
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractExecutionHandler.java

[JENKINS-46511]([JENKINS-46511] Only trigger downstream pipelines if maven builds reach a threshold lifecycle phase) Only trigger downstream pipelines if maven builds reach a threshold lifecycle phase
The default minimum lifecycle phase is "deploy", can be configured to trigger downstream pipeline on "install" or on "package"

[JENKINS-46511] Only trigger downstream pipelines if maven builds reach a threshold lifecycle phase

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractExecutionHandler.java

[JENKINS-47508](https://issues.jenkins-ci.org/browse/JENKINS-47508) Fix NPE when `executionId` is missing

[JENKINS-47508] Fix NPE when executionId is missing

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java

[JENKINS-48362](https://issues.jenkins-ci.org/browse/JENKINS-48362) Regression: 3.0.3 no longer support whitespace in Maven installation path

[JENKINS-48362] Support whitespace in Maven installation path

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenConfigFolderOverrideProperty.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/MavenConfigFolderOverrideProperty/config.jelly
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/MavenConfigFolderOverrideProperty/help-Settings.html
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/MavenConfigFolderOverrideProperty/help-globalSettings.html
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java

https://issues.jenkins-ci.org/browse/JENKINS-48678
- This change allows define Maven Settings and Maven Global Settings at a folder level
- Logs for these settings have been refactored so only one line is printed per settings file and only if log level is set to `Level.FINE`. Examples:
```
[withMaven] using Maven settings provided by the Jenkins global configuration. Maven settings on the build agent'/Users/alobato/.m2/settings.xml'
[withMaven] using Maven global settings provided by the Jenkins global configuration. Maven global settings on the build agent '/Users/alobato/.m2/settings.xml'
[withMaven] using overriden Maven settings by folder 'folder'. Config File Provider maven settings file 'FolderSettings'
[withMaven] using overriden Maven global settings by folder 'folder'. Config …
```

[JENKINS-48678] - Define Maven Settings and Global Maven Settings at the folder level.

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/MavenLinkerPublisher.java
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/MavenLinkerPublisher/config.jelly
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/MavenLinkerPublisher/help-disabled.html
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/MavenLinkerPublisher/help.html
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/MavenLinkerPublisher/summary.jelly
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/MavenPublisherTest.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/ArtifactDeployedEventHandler.java

[JENKINS-49334](https://issues.jenkins-ci.org/browse/JENKINS-49334) MavenLinkerPublisher option
**MavenLinkerPublisher** is an optional publisher to **withMaven()** to publish links of deployed artifacts.
Unlike **GeneratedArtifactsPublisher**, **MavenLinkerPublisher** does not archive artifacts on master; simply track the deployed artifacts and display the url.

[JENKINS-49334] MavenLinkerPublisher option

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/trigger/WorkflowJobDependencyTrigger.java

[This](https://github.com/jenkinsci/pipeline-maven-plugin/blob/b06db243e39c890fedb41dede8c6ef093978390e/jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/trigger/WorkflowJobDependencyTrigger.java#L28-L31) and [this](https://github.com/jenkinsci/pipeline-maven-plugin/blob/b06db243e39c890fedb41dede8c6ef093978390e/jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java#L143-L163) indicate that the generic type was incorrect.
@reviewbybees

WorkflowJobDependencyTrigger is not only applicable to Job so its signature was wrong

---

jenkins-plugin/pom.xml

Can revert #85 as it is unnecessary as of a change made in #82, though https://github.com/jenkinsci/junit-attachments-plugin/pull/18 has also been released as 1.5 if you want it.
@reviewbybees

[INFRA-1310] Reverting obsolete exclusion

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/InvokerRunsPublisher.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/FileUtils.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/publishers/InvokerRunsPublisherTest.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/FileUtilsTest.java
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-maven-invoker-plugin-integration-tests.xml

[JENKINS-49898](https://issues.jenkins-ci.org/browse/JENKINS-49898) maven-invoker-plugin add support for relative path in "reportsDirectory", "projectsDirectory" and "cloneProjectsTo"

[JENKINS-49898] maven-invoker-plugin: add support for file relative path

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-jdk.html
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-maven.html

Extend `detectWithContainer` to support builds running in kubernetes pods provided by the jenkins-kubernetes plugin

Detect builds running in kubernetes containers

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/AbstractHealthAwarePublisher.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/FindbugsAnalysisPublisher.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher.java

[JENKINS-50508] extract dependencies to the "Static Code Analysis Plug-ins", to the package `hudson.plugins.analysis.core` or other plugins outside of `org.jenkinsci.plugins.pipeline.maven.MavenPublisher` sub classes to prevent class loading issues and NPE when the related plugins are not installed.

[JENKINS-50508] extract dependencies to the "Static Code Analysis Plug-ins"

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java

by surrounding the whole -D statement with quotes (`"-Dmaven.repo.local=/bla/blub"` instead of `-Dmaven.repo.local="/bla/blub"`), the local repo works with maven wrapper as well as with standalone maven.

JENKINS-51073 Quick fix for quote problems

---

jenkins-plugin/pom.xml

[JENKINS-51224] make workflow-job a required dependency, otherwise DownstreamPipelineTriggerRunListener causes an exception

[JENKINS-51224] make workflow-job a required dependency

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java

[JENKINS-53396] Verify downstream pipeline eligibility only once when multiple generated maven artifacts trigger a pipeline
Troubleshooting message style when an eligibility check is skipped and when the logger `org.jenkinsci.plugins.pipeline.maven.listeners.DownstreamPipelineTriggerRunListener=FINEST`:
```
[withMaven - DownstreamPipelineTriggerRunListener] Skip eligibility check of pipeline dependency-graph/my-downstream-of-a-multi-jar-project/master for artifact com.example.multi-jar:jar-2:jar:0.0.1-SNAPSHOT(0.0.1-20180903.201513-17), eligibility already confirmed
```

[JENKINS-53396] Verify downstream pipeline eligibility only once when  multiple generated maven artifacts trigger a pipeline

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java

If the flatten-maven-plugin is used to created a flattened pom (i.e. a BOM) and to replace the original POM of a project, the Maven Event Spy reverts the flattened POM to the original POM.
Due to this the original POM is archived in Jenkins instead of the flattened one.
This behavior of the Maven Event Spy has been introduced by JENKINS-43616 .
While this might be a valid workaround for the "dependency-reduced-pom.xml" issue ( JENKINS-42302 ), where only a temporary POM is created, it is the intended behavior of the maven-flatten-plugin to replace the original POM by the flattened one as the main build artifact and it therefore should be archived instead of the original one.

Exclude flattened POMs from being replaced by the original POM in Maven Event Spy.

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/service/PipelineTriggerService.java
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-jdk.html
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-maven.html
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-mavenLocalRepo.html
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-mavenOpts.html
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help.html

Fixes Javadoc processing errors with latest Java

Java 11 cleanup - change <tt> to <code> in Javadoc

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/console/MaskSecretsOutputStream.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/console/MavenColorizerConsoleLogFilter.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/console/MavenConsoleAnnotator.java

[JENKINS-54133](https://issues.jenkins-ci.org/browse/JENKINS-54133)
Analogue of https://github.com/jenkinsci/ant-plugin/pull/32.

 [JENKINS-54133] JEP-210 compatibility for console filters

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/AbstractPipelineMavenPluginDao.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2v1Dao.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/db/migration/MigrationStep.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2DaoInitializationTest.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2v1DaoInitializationTest.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginMySqlDaoInitializationTest.java

JENKINS-55370 prevent cases where `jenkins.rootUrl` is `null` during the initialization of the pipeline-maven-plugin and update the `jenkins_master.url if the url has changed.

JENKINS-55370 prevent cases where `jenkins.rootUrl` is `null` during the initialization 

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginMySqlDao.java
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig/config.jelly
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig/help-jdbcUrl.html
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginMySqlDaoTest.java

JENKINS-55378 Add support for MariaDB. If MariaDB is detected, an info message "MariaDB version x.y.z detected. Please ensure that your MariaDB version is at least version 10.2+" is displayed

JENKINS-55378 Add support for MariaDB

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java

[JENKINS-56232](https://issues.jenkins-ci.org/browse/JENKINS-56232) mavenLocalRepo: support absolute folder path in addition to relative folder path

JENKINS-56232 mavenLocalRepo: support absolute folder path

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java

JENKINS-56666 maven-git-versioning-extension causes warnings due to temporary pom.xml file name '.git-versioned.pom.xml'

JENKINS-56666 better support of maven-git-versioning-extension

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2Test.java

JENKINS-57324 Fix '%' char escaping in the windows batch script wrapper for mvn.cmd

JENKINS-57324 Fix '%' char escaping in the windows batch script wrapper for mvn.cmd

---

jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitor/message.jelly

Fix the typo and use the modern styling fro administrative warnings.

update typo and styling of admin monitor

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/AbstractPipelineMavenPluginDao.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginDao.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginMonitoringDao.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginNullDao.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/MavenReport/index.jelly
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/MavenReport/jobMain.jelly
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/MavenReport/summary.jelly
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginDaoAbstractTest.java

Considering two Maven artefacts having same groupId / artifactId / version and same type or `null` classifier or same classifier to be the same

JENKINS-59500 feature: Downstream pipelines are not triggered when the artifact has type docker-info

---

jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_nbm_base_project/pom.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_nbm_dependency_project/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher.java

Thycho Surefire Plugin is under group `org.eclipse.tycho` and not `org.apache.maven.plugins`.

[JENKINS-61790] Fix groupId used to detect executions of the Tycho Surefire Plugin

---

maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/AbstractMavenEventHandler.java

The exception message captured by the maven spy contains ANSI Escape sequences (coloring) when maven is executed with console coloring enabled. These escape codes are not valid XML characters and must be stripped from the message before being written in the XML file.

[JENKINS-61791] Strip Ansi Color escape sequences from captured exceptions

---

jenkins-plugin/pom.xml
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
maven-spy/pom.xml
pom.xml

* Use BOM for Jenkins 2.204.x + cleanup as much as possible the dependencies
* Bump Jenkins core requirement 2.138.4 -> 2.204.6
* Bump plugin parent 3.43 -> 4.6
It's a draft, I have to review more deeply the list of changes .... (it's a nightmare)
```
-[INFO]    com.google.code.findbugs:annotations:jar:3.0.1:compile (optional)
-[INFO]    com.google.code.findbugs:jsr305:jar:3.0.1:compile
```
```
```
```
-[INFO]    args4j:args4j:jar:2.0.31:provided
-[INFO]    com.github.jnr:jffi:jar:1.2.15:provided
-[INFO]    com.github.jnr:jffi:jar:native:1.2.15:provided
-[INFO]    com.github.jnr:jnr-constants:jar:0.9.8:provided
-[INFO]    com.github.jnr:jnr-ffi:jar:2.1.4:provided
-[INFO]    com.github.jnr:jnr-posix:jar:3.0.41:provided
+[INFO]    args4j:args4j:jar:2.33:provided
+[INFO] …
```

Jenkins core upgrade (2.138.4 -> 2.204.6) + Plugin parent upgrade (3.43 -> 4.6) + BOM

---

README.adoc

The plugins site already shows past security issues in the  right hand pane.  I don't think it helps readers to show the past security issues in two locations.
The git client plugin uses an asciidoc README and the security issues look like this:

Let the plugins site show past security issues

---

jenkins-plugin/pom.xml

It overrides the update we did in the parent pom and prevents to deploy the new documentation on plugins.jenkins.io

[fix] The URL in the plugin pom was still referencing confluence

---

jenkins-plugin/pom.xml
maven-spy/pom.xml

Otherwise the plugin get this invalid URL for the doc : https://github.com/jenkinsci/pipeline-maven-plugin/blob/master/README.adoc/pipeline-maven

[fix] Enforce the url in the submodules

---

jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_nbm_base_project/pom.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_nbm_dependency_project/pom.xml

Amends #156: after the transition to Apache NetBeans, the old Maven repository is dead and artifacts are not publicly available in general. (Some have been mirrored to the Jenkins Artifactory but better not rely on that!) Should fix the test failure noted in https://github.com/jenkinsci/pipeline-maven-plugin/pull/290#issuecomment-707549911. CC @JaroslavTulach

bits.netbeans.org Maven repo is dead

---

jenkins-plugin/pom.xml

These dependencies are now using the version available in the BOM
* org.jenkins-ci.plugins.workflow:workflow-multibranch:jar:2.22:test
* org.jenkins-ci.plugins:htmlpublisher:jar:1.23:compile (optional)
* org.jenkins-ci.plugins:pipeline-stage-step:jar:2.5:test

Use BOM versions when available

---

README.adoc
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenConfigFolderOverrideProperty.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/TaskListenerTraceWrapper.java
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/config.jelly
jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-traceability.html
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java

Adds a verbose parameter to the step execution, defaults to true, so the initial behaviour is not changed.
Can turn of the version info and the `----- withMaven Wrapper script -----` line
Fixes https://issues.jenkins.io/browse/JENKINS-58425

Allow to silent traceability information

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisher.java

The current pipeline-maven-plugin currently does not support/include any prepare-agent-integration goals created output files to the list of jacoco destination files that will be included in the jacoco published results when doing
withMaven(..., options: [jacocoPublisher(disabled: false)])
This pull request will add the destination files created as a result of prepare-agent-integration goals.

Add the missing agent-prepare-integration goals to the jacoco publisher list

---

FAQ.adoc

Added a third way to the FAQ under _How to use the Pipeline Maven Plugin with Docker?_: `MVN_CMD` 
I also fixed a missing `'` in the `MVN_CMD_DIR` example.
I consider `MVN_CMD` the least intrusive way.

Document MVN_CMD as an alternative to MVN_CMD_DIR and mvnw

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2Dao.java

If the H2 db has been started to use a local DB server (inside this JVM)
then we need to ensure it is shutdown.
The database would only be cleanly shutdown previously on a clean JVM
shutdown which caused issues if
1. Jenkins was running in a web container and the webapp was restarted
rather than the whole app
2. Jenkins tests where the plugin was present.
Additionally it seems that in some cases (pipeline jobs?) `RunListeners` can be fired after Jenkins starts shutting down, which resulted in the database being opened (and prevented tests from terminating)

Ensure the H2 DB is shutdown on Jenkins termination

---

jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitor/message.jelly

The admin monitor for the non production database was not using the expected format and thus was styled rather funkily.

Fix layout of admin monitor

---

jenkins-plugin/pom.xml
pom.xml

https://www.jenkins.io/changelog-stable/ (2021-03-10)

Bump Jenkins core requirement from 2.204.6 to 2.277.1

---

.github/dependabot.yml

Add myself to dependabot pull requests reviewers, to be notified
- [N/A] Link to relevant issues in GitHub or Jira
- [N/A] Link to relevant pull requests, esp. upstream and downstream changes
- [N/A] Ensure you have provided tests - that demonstrates feature works or fixes the issue

chore: add myself as reviewer for dependabot pull requests

---

jenkins-plugin/pom.xml
jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepGlobalToolTest.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepMavenExecResolutionTest.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/docker/MavenWithMavenHomeJavaContainer.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/docker/NonMavenJavaContainer.java
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/MavenWithMavenHomeJavaContainer/Dockerfile
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/NonMavenJavaContainer/Dockerfile

allow recognizing Maven through non-system-wide defined MAVEN_HOME env var (fixes JENKINS-43651)

[JENKINS-43651] allow recognizing Maven through non-system-wide defined MAVEN_HOME env var

---

jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/AbstractIntegrationTest.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_deployfile_base_project/pom.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_deployfile_dependency_project/pom.xml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_deployfile_dependency_project/src/main/java/com/example/App.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java
maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/DeployDeployFileExecutionHandler.java
maven-spy/src/test/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/DeployDeployFileExecutionHandlerTest.java

Adds a new `ExecutionHandler` for the `JenkinsMavenEventSpy` wich checks if the `MojoExecution` of the goal `org.apache.maven.plugins:maven-deploy-plugin:deploy-file` contains a lifecycle. When no lifecycle is present it assumes the `deploy`-Lifecycle.
https://issues.jenkins.io/browse/JENKINS-67507

[JENKINS-67507] Artifacts deployed by direct invocation of deploy-file goal don't trigger downstream builds

---

jenkins-plugin/pom.xml
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeTest.java
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_default.yml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_mysql.yml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_postgresql.yml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_publishers.yml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_triggers.yml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_default.yml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_mysql.yml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_postgresql.yml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_publishers.yml
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_triggers.yml

Pipeline maven plugin can be configured through Configuration as Code. We should submit examples on the CasC repository, but for that, we should prove that we support such configurations.

JENKINS-65001: add test for CasC

---

.mvn/wrapper/maven-wrapper.properties

Recent maven version is forced by enforcer plugin
Use a recent maven version to build the plugin.

chore: update maven version pulled by wrapper

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfigTest.java

The generic properties must be passed to Hikari in the constructor of `HikariConfig` otherwise they are not fully applied in the expected way. To maintain backward compatibility, I've also added the former `dsConfig.setDataSourceProperties(p)`, so that the properties are also still fully available as data source properties.
Fixes https://issues.jenkins.io/browse/JENKINS-69375
Did manual testing only.

JENKINS-69375 ensure properties are passed to Hikari

---

pom.xml

Using the main repository URL is needed for third parties like plugins.jenkins.io.

fix: Use proper GH URL

---

jenkins-plugin/pom.xml

README's are detected automatically by the update center or plugins.jenkins.io, directly linking to the readme breaks file references.

Fix URL linking

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher.java

Use the new method which supports the Jenkins JUnit [SQL storage](https://plugins.jenkins.io/junit-sql-storage/).
The old parseAndAttach is deprecated and can't publish test results when using SQL storage

Use JUnitResultArchiver#parseAndSummarize method 

---

jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitor/message.jelly

Reverts jenkinsci/pipeline-maven-plugin#547 because we're reverting the core PR.

Revert "Forward compatibility with jenkins-buttons"

---

pom.xml

Without this, the Jenkins plugin module inherits from this property, adding its name to the URL.
However, this is not generating valid url.
This create a problem in plugins.jenkins.io/pipeline-maven as the data is coming from the Update Center.

Fixes plugin scm link

---

jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/AbstractIntegrationTest.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepNoOptionalsTest.java

The previous url may contain only 3 maintained versions of Apache products. So it's not guarantee to contains old versions. And I did some cleanup on the dist area and removed few versions. sorry for that. But now I fix this here :)
```[tasklist]
```

Fix url to download Apache Maven binary

---

maven-spy/pom.xml
pom.xml

_🤖 This is an automatic PR for replacing the deprecated 'hamcrest-*' modules with 'hamcrest'._
All deprecated modules' code has been merged into 'hamcrest'.
Consumers of `hamcrest-*` should replace the dependency with `hamcrest`, which is the drop-in module containing the code of the deprecated `hamcrest-*` modules.
Ping `@NotMyFault` if you have questions.
_[script source](https://github.com/NotMyFault/jenkins-version-updater)_

Replace deprecated 'hamcrest-*' modules with 'hamcrest'

---

jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepRestartTest.java

As of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180, `FilePath` is not supposed to be directly serialized in program state, because it is tricky to resume a Java object referring to a live agent channel. `WithMavenStepExecutionCallBack` unfortunately did so, unlike say https://github.com/jenkinsci/credentials-binding-plugin/blob/8c080630bc65ef1eb1183d0e5cc179dc486122c0/src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/UnbindableDir.java#L72 which would be used in
```groovy
node(…) {
withCredentials([file(…)]) {
sh '…'
}
}
```
This could mean that if an agent failed to reattach to the controller after a restart, a build could hang indefinitely with a message like
```
Still trying to load Looking for path named …
```

Do not rely on `FilePathPickle`

---

jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/JavaGitContainer/Dockerfile
maven-spy/pom.xml

not sure if java 1.6 is really the goal but since the parent pom upgrade the compilation was made using release flag 11 so this will not work on older java versions (due to https://github.com/jenkinsci/pipeline-maven-plugin/commit/81e7ff8d6f2d3af48566f4054803488ea1390e66)
fix https://issues.jenkins.io/browse/JENKINS-71949
Signed-off-by: Olivier Lamy <olamy@apache.org>

JENKINS-71949 : restore Java 6/7/8 compatibility

---

pipeline-maven-spy/pom.xml
pom.xml

Remove support for Java 6 and Java 7 builds.
While these are really old and unsupported version for a while now, clearly express to users that it is a breaking change
```[tasklist]
```

chore: drop Java 6/7 support

---

pipeline-maven/pom.xml
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java

`jenkinsci/bom` builds run without Docker, but this plugin assumes that Docker is available in all Unix environments. Our general pattern in Jenkins plugins is to use Docker when it is available, but otherwise to skip the tests when Docker is not available rather than to fail: this pattern is employed by lots of other plugins that use Docker and allows us to run at least the majority of tests in `jenkinsci/bom` builds without having to resort to expensive VMs. This PR makes this plugin consistent with other plugins by skipping the Docker tests when running on a Unix system without Docker (e.g., our `jenkinsci/bom` builds).
Ran `mvn clean verify` in a Java 11 Docker container (i.e., an environment without Docker). Before this PR, the build failed; after this PR, it passes.

Attempt to use Docker on Unix systems only when Docker is running

---

pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersion.java
pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionUtils.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/MavenUtil.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionTest.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionUtilsTest.java

See https://issues.jenkins.io/browse/JENKINS-72386
```[tasklist]
```

fix JENKINS-72386: withMaven exits with unrecognized option --no-transfer-progress when using maven < 3.6.1

---

pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeNeedDockerTest.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfigTest.java

As seen in #754 this is necessary to make tests pass. Broken by https://github.com/docker-library/mysql/pull/1024 / https://github.com/docker-library/official-images/pull/16088 AFAICT. Detected by a @cloudbees PCT regression. In case anyone cares
```
[main] ERROR tc.mysql:8.3.0 - Log output from the failed container:
2024-01-19 17:54:12+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.3.0-1.el8 started.
2024-01-19 17:54:12+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-01-19 17:54:12+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.3.0-1.el8 started.
2024-01-19 17:54:12+00:00 [Note] [Entrypoint]: Initializing database files
2024-01-19T17:54:12.538592Z 0 [System] [MY-015017] [Server] MySQL Server Initialization - start. …
```

chore: temporarily pin `mysql` image to avoid test regressions

---

pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java

The **detectWithContainer** method within **WithMavenStepExecution2** that detects whether a withMaven step is called inside a container (inside the **docker.image()** block from the [Docker Pipeline plugin](https://plugins.jenkins.io/docker-workflow) or the **container()** block from the [Kubernetes plugin](https://plugins.jenkins.io/kubernetes)) does not work as described for the **container()** step.
Console log of the withMaven execution inside container() block (with WithMavenStepExecution2 FINEST logging level):
Before:
```
[withMaven] Options: []
[withMaven] Available options: 
[withMaven] using JDK installation provided by the build agent
[withMaven] using Maven settings provided by the Jenkins Managed Configuration File 'maven-settings' 
[withMaven] using Maven settings.xml …
```

Fix detection if withMaven is executed within container()

---

pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/cli/TriggerDownstreamPipelinesCommand.java
pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncItemListener.java
pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncRunListener.java
pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncRunListenerTest.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListenerTest.java

While Jenkins core technically supports Guice, it is not recommended as it is used by a very small number of plugins and the Guice integration with the Jenkins extension subsystem is very complex and fragile. To make matters worse, a future version of Guice (version 7) will drop support for `javax.inject` imports in favor of `jakarta.inject` imports. To prepare for this inevitable migration, this PR drops usage of Guice in favor of traditional static injection, which is the common pattern throughout the Jenkins ecosystem. In this way, this plugin will stop being dependent on a particular version of Guice, enabling us to eventually upgrade Guice in Jenkins core to version 7 without impacting this plugin. This PR does make the Mockito tests a little less elegant, but the Jenkins project …

Reduce usage of Guice

---

pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java

Otherwise reading the generated files by maven may fail on platforms as z/OS. Furthermore, by default maven assumes UTF-8 when reading settings.
Summary:  Maven fails to read platform encoded settings files on z/OS but should always (platform independent) succeed reading UTF-8 encoded setting files. Hence, let pipeline-maven-plugin write with UTF-8 encoding instead of platform encoding.
For a detailed problem description see [Jenkins-72529](https://issues.jenkins.io/browse/JENKINS-72529). 
- successfully run withMaven(mavenSettingsConfig: '...', ... ) step on z/OS node
- mvn verify on linux - no failing tests
```[tasklist]
```

[JENKINS-72529] write settings file always in UTF-8 encoding

---

pipeline-maven/pom.xml

When running Plugin Compatibility Tester (PCT) against a version of Jenkins core with ASM removed and against a JaCoCo plugin with a dependency on the ASM library plugin in https://github.com/jenkinsci/bom/pull/3019, `org.jenkinsci.plugins.pipeline.maven.publishers.JacocoReportPublisherTest` failed with
```
java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
at …
```

Stop excluding ASM via the plugin system

---

pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java

This test started failing recently, at least in CI (cannot yet reproduce locally); see https://github.com/jenkinsci/pipeline-maven-plugin/pull/795/checks?check_run_id=25521476848 for an example. Possibly due to https://github.com/git/git/commit/9e65df5eab274bf74c7b570107aacd1303a1e703 (thx @cathychan) https://github.blog/2024-05-14-securing-git-addressing-5-new-vulnerabilities/

Set `safe.directory` in `WithMavenStepTest.tesWithDifferentJavasForBuild`

---

FAQ.adoc
README.adoc

Message warning has been removed in commit c2ebbacab5cc10e974a322ed173cf4fc3815f836 (JENKINS-49337 add backward compatibility)
https://github.com/takari/maven-wrapper
https://github.com/jenkinsci/pipeline-maven-plugin/pull/745

Replace deprecated Takari wrapper with official one

---

pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2Test.java

Restores with container detection handling back to 1376.v18876d10ce9c. This version contained special handling for kubernetes-plugin as well as naming convention for other plugins to trigger special with container handling.
This fixes a regression introduced by #774 for plugins using the `ContainerExecDecorator` detection path, not including
kubernetes-plugin container step. Without this special handling steps that use maven inside a container cause the agent to quit unexpectedly. 
Tested with local plugin build.
```[tasklist]
```

Revert to 1376.v18876d10ce9c detectWithContainer logic

---

pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersion.java
pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionUtils.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionUtilsTest.java

Using Maven 4.0.0-beta-3, this plugins warns with:
> [withMaven] WARNING: You are running an old version of Maven (UNKNOWN), you should update to at least 3.8.x

Adds support to detect Maven 4 beta versions

---

pipeline-maven/pom.xml
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepMavenExecResolutionTest.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/docker/JavaGitContainerTest.java
pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/JavaGitContainer/Dockerfile
pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/SshdContainer/Dockerfile
pom.xml

This PR updates the test suite to support versions of Jenkins core that are compiled with Java 17 bytecode, as a forthcoming weekly soon will be this month.
I was testing the plugin with `maven.compiler.{testR,r}elease` set to `17` to generate a Java 17 binary. While doing so, I kept getting
```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (build-first-sshd-image) on project pipeline-maven: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.lang.UnsatisfiedLinkError: could not load FFI provider com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.Provider: ExceptionInInitializerError: Can't overwrite cause with java.lang.UnsatisfiedLinkError: …
```

Forward compatibility for Java 17 bytecode

---

pom.xml

No need to declare it in the dependency management section when is included as a transitive dependency as needed by the tests.
Confirmed that automated tests pass on Linux with JDK 21.0.4

Remove byte buddy dependency declaration

---

pipeline-maven-api/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenArtifact.java
pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtilsTest.java
pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-deploy-jar.xml
pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/maven-spy-include-attached-artifacts.xml

1. As mentioned by recent comments on [JENKINS-69410](https://issues.jenkins.io/browse/JENKINS-69410?focusedId=442796&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-442796) there are still broken URL links created for artifacts deployed. Those links are related to artifacts that are attached in addition to a modules primary artifacts.
e.g. -sources.jar artifacts attached by the Maven sources plugin do not get proper links in case the deploy plugin will create time stamped filenames deployed (which is the most common usage for deployed snapshot artifacts).
2. If the deploy repository URL configured is ending with a `/` character, then the deployed artifact URL link is containing a `//`. This issue is fixed by this PR as well.
s. details in the commit comment …

fix JENKINS-69410: Links to Attached Artifacts broken

---

pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
pom.xml

Migrate from deprecated EE 8 functionality to non-deprecated EE 9 equivalents.
CI build

Switch to 2.479 baseline and migrate from EE 8 to EE 9

---

pipeline-maven/pom.xml
pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java

Remove the `test` artifact dependency on the `junit-plugin` in order to resolve test failure reported by https://github.com/jenkinsci/bom/pull/5041
I copied the now inaccessible assertion methods in order to break the dependency as I found that to be the easiest solution.
This change needs to be released in order to fix the test failure in `bom`.
@basil @timja FYI
`mvn clean verify`

Remove test dependency to junit plugin test artifact
